################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
# EXECUTABLE	:= bruteforcematcher_pagelockedmem
EXECUTABLE	:= bruteforcematcher
# keep		:= 1
# CUDA source files (compiled with cudacc)
CUFILES_sm_12		:= bruteforcematcher.cu
# CUFILES_sm_20		:= bruteforcematcher.cu
# CUDA dependency files
#CU_DEPS		:= \
	template_kernel.cu \

# C/C++ source files (compiled with gcc / c++)
# CCFILES		:= \
#	template_gold.cpp \


################################################################################
# Rules and targets

include ../../common/common.mk
