################################################################################

# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= horspoolmatcher
# CUDA source files (compiled with cudacc)
# CUFILES_sm_20		:= horspoolmatcher.cu
 CUFILES		:= horspoolmatcher.cu
# CUDA dependency files
# CU_DEPS		:= \
	template_kernel.cu \

# C/C++ source files (compiled with gcc / c++)
# CCFILES		:= \
	template_gold.cpp \


################################################################################
# Rules and targets

include ../../common/common.mk
